---
- hosts: 
  gather_facts: no
  tasks:
  - name: Verifying virtualbox installation
    shell: dpkg -l | grep virtualbox-5.1 | awk '{print $3}'
    register: out

  - debug: var=out.stdout_lines

  - name: Installing VirtualBox 5.1
    apt: name=virtualbox=5.1 state=present
    when: out != "5.1.8-111374~Ubuntu~trusty"
    tags: vboxinstall

  - name: Verifying virtualbox installation
    shell: dpkg -l | grep virtualbox-5.1 | awk '{print $3}'
    register: out
    
  - debug: var=out.stdout_lines
